import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by `npm run gen:api` from api-spec/scout-api.openapi.json.
// Spliced in below rather than autogenerated from the filesystem, because
// the endpoint order comes from the spec's tags, not from filenames.
import scoutApiSidebar from './docs/api/reference/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'introduction',
    'getting-started',
    {
      type: 'category',
      label: 'Scout CLI',
      items: [{type: 'autogenerated', dirName: 'scout-cli'}],
    },
    {
      type: 'category',
      label: 'Scout MCP',
      items: [{type: 'autogenerated', dirName: 'scout-mcp'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Instrument',
      items: [{type: 'autogenerated', dirName: 'instrument'}],
    },
    {
      type: 'category',
      label: 'Operate',
      items: [{type: 'autogenerated', dirName: 'operate'}],
    },
    {
      type: 'category',
      label: 'Observe',
      items: [{type: 'autogenerated', dirName: 'observe'}],
    },
    {
      type: 'category',
      label: 'API',
      link: {type: 'doc', id: 'api/index'},
      items: [
        'api/quickstart',
        'api/authentication',
        'api/conventions',
        'api/errors',
        {
          type: 'category',
          label: 'Endpoint reference',
          items: scoutApiSidebar,
        },
      ],
    },
  ],
};

export default sidebars;
