const ENABLE_ALGOLIA_CRAWLER = process.env.ENABLE_ALGOLIA_CRAWLER || "false";
const ALGOLIA_APP_ID = process.env.ALGOLIA_APP_ID || "";
const ALGOLIA_SEARCH_API_KEY = process.env.ALGOLIA_SEARCH_API_KEY || "";
const ALGOLIA_DOCSEARCH_INDEX_NAME = process.env.ALGOLIA_DOCSEARCH_INDEX_NAME || "";

export { ENABLE_ALGOLIA_CRAWLER, ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY, ALGOLIA_DOCSEARCH_INDEX_NAME };