import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/reference/scout-api",
    },
    {
      type: "category",
      label: "telemetry",
      link: {
        type: "doc",
        id: "api/reference/telemetry",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/list-traces",
          label: "List traces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/get-trace",
          label: "Get trace details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/discover-logs",
          label: "Discover log schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/query-logs",
          label: "Query logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/discover-spans",
          label: "Discover span schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/discover-metrics",
          label: "Discover metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/query-metrics",
          label: "Query metrics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "services",
      link: {
        type: "doc",
        id: "api/reference/services",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/list-services",
          label: "List services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/get-service-topology",
          label: "Get service topology",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/get-service-dependencies",
          label: "Get service dependencies",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/get-service-profile",
          label: "Get service profile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/get-service-metrics",
          label: "Get service metrics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "apm",
      link: {
        type: "doc",
        id: "api/reference/apm",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/apm-list-services",
          label: "List APM services",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/apm-get-kpis",
          label: "Get APM service KPIs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/apm-list-operations",
          label: "List APM operations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/apm-list-facet-values",
          label: "List APM facet values",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "rum",
      link: {
        type: "doc",
        id: "api/reference/rum",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/rum-list-crashes",
          label: "List RUM crashes",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-list-apps",
          label: "List RUM applications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-get-kpis",
          label: "Get RUM KPIs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-list-sessions",
          label: "List RUM sessions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-list-users",
          label: "List RUM users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-list-screens",
          label: "List RUM screen performance",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/reference/rum-list-http",
          label: "List RUM HTTP endpoints",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "alerts",
      link: {
        type: "doc",
        id: "api/reference/alerts",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/list-alerts",
          label: "List alerts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "system",
      link: {
        type: "doc",
        id: "api/reference/system",
      },
      items: [
        {
          type: "doc",
          id: "api/reference/get-system-health-summary",
          label: "Get system health summary",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/reference/schemas/listtracesresponse",
          label: "ListTracesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/tracelistitem",
          label: "TraceListItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/llmattributessummary",
          label: "LLMAttributesSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/paginationmeta",
          label: "PaginationMeta",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/tracedetailresponse",
          label: "TraceDetailResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/spandetail",
          label: "SpanDetail",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/spanevent",
          label: "SpanEvent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/spanlink",
          label: "SpanLink",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/llmattributes",
          label: "LLMAttributes",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/errorresponse",
          label: "ErrorResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumcrashlistresponse",
          label: "RumCrashListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumcrashgroup",
          label: "RumCrashGroup",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumapplistresponse",
          label: "RumAppListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumappsummary",
          label: "RumAppSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumkpisresponse",
          label: "RumKpisResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumkpisummary",
          label: "RumKpiSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumkpipoint",
          label: "RumKpiPoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumcrashpoint",
          label: "RumCrashPoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumsessionlistresponse",
          label: "RumSessionListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumsessionitem",
          label: "RumSessionItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumuserlistresponse",
          label: "RumUserListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumuseritem",
          label: "RumUserItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumscreenlistresponse",
          label: "RumScreenListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumscreensummary",
          label: "RumScreenSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumhttplistresponse",
          label: "RumHTTPListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/rumhttpendpoint",
          label: "RumHTTPEndpoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/listservicesresponse",
          label: "ListServicesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicetopologyresponse",
          label: "ServiceTopologyResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicedependenciesresponse",
          label: "ServiceDependenciesResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/serviceprofileresponse",
          label: "ServiceProfileResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/profilerelationship",
          label: "ProfileRelationship",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicemetricsresponse",
          label: "ServiceMetricsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/serviceinfo",
          label: "ServiceInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicedependency",
          label: "ServiceDependency",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicemetric",
          label: "ServiceMetric",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/logdiscoveryresponse",
          label: "LogDiscoveryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/logqueryresponse",
          label: "LogQueryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/logentry",
          label: "LogEntry",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/timerange",
          label: "TimeRange",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/severitycount",
          label: "SeverityCount",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/spandiscoveryresponse",
          label: "SpanDiscoveryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/statuscodecount",
          label: "StatusCodeCount",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/metricdiscoveryresponse",
          label: "MetricDiscoveryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/metricinfo",
          label: "MetricInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/metricqueryresponse",
          label: "MetricQueryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/metricseries",
          label: "MetricSeries",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/metricdatapoint",
          label: "MetricDataPoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/systemhealthsummaryresponse",
          label: "SystemHealthSummaryResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/firingalertinfo",
          label: "FiringAlertInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/servicehealthinfo",
          label: "ServiceHealthInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/relationshipstats",
          label: "RelationshipStats",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/listalertsresponse",
          label: "ListAlertsResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/alertinfo",
          label: "AlertInfo",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmservicelistresponse",
          label: "ApmServiceListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmservicesummary",
          label: "ApmServiceSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmpreviouswindow",
          label: "ApmPreviousWindow",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmsparklinepoint",
          label: "ApmSparklinePoint",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmtotals",
          label: "ApmTotals",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmkpisresponse",
          label: "ApmKpisResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmkpisummary",
          label: "ApmKpiSummary",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmoperationlistresponse",
          label: "ApmOperationListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmoperation",
          label: "ApmOperation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmfacetlistresponse",
          label: "ApmFacetListResponse",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmfacetvalue",
          label: "ApmFacetValue",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/reference/schemas/apmtimeseriespoint",
          label: "ApmTimeseriesPoint",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
